services:
  database:
    image: mariadb:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    volumes:
      - records:/var/lib/mysql
volumes:
  records:
    driver: local